routes/web.php
<?php

require __DIR__ . '/web/admin.php';
require __DIR__ . '/web/employer.php';
require __DIR__ . '/web/common.php';

app/Models/Company.php
<?php

namespace App\Models;

use App\Helpers\PathHelper;
use App\Helpers\ImageHelper;
use App\Models\CompanyReview;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Company extends Model
{
    use SoftDeletes, Notifiable;
    
    protected $fillable = [
        'name',
        'slug',
        'logo',
        'banner',
        'short_description',
        'address',
        'country_id',
        'province_id',
        'city_id',
        'city_name',
        'subdistrict_id',
        'pos_code',
        'phone',
        'email',
        'website_url',
        'instagram',
        'facebook',
        'linkedin',
        'twitter',
        'description',
        'images',
    ];

    protected $casts = [
        'images' => 'array'
    ];

    public static function boot()
    {
        parent::boot();

        static::deleting(function ($company) {
            if ($company->forceDeleting) {
                // Delete directory
                $path = PathHelper::company_path($company->id);
                PathHelper::deleteDirectory($path);

                $company->work_jobs()->forceDelete();
                $company->industries()->forceDelete();
                $company->company_reviews()->forceDelete();
            } else {
                $company->work_jobs()->delete();
                $company->industries()->delete();
                $company->company_reviews()->delete();
            }
        });

        static::restored(function ($company) {
            $company->work_jobs()->restore();
            $company->industries()->restore();
            $company->company_reviews()->restore();
        });
    }

    public function employers()
    {
        return $this->belongsToMany('App\Models\Employer');
    }

    public function work_jobs()
    {
        return $this->hasMany('App\Models\Workjob', 'company_id');
    }

    public function country()
    {
        return $this->belongsTo('App\Models\Country');
    }

    public function province()
    {
        return $this->belongsTo('App\Models\Province');
    }

    public function city()
    {
        return $this->belongsTo('App\Models\City');
    }

    public function subdistrict()
    {
        return $this->belongsTo('App\Models\Subdistrict');
    }

    public function industries()
    {
        return $this->belongsToMany('App\Models\Industry');
    }

    /**
     * Get all of the company_reviews for the Company
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function company_reviews(): HasMany
    {
        return $this->hasMany(CompanyReview::class);
    }

    public function getCityNameAttribute()
    {
        return is_null($this->city_id) ? $this->city_name : $this->city->name;
    }

    public function getLogoUrlAttribute()
    {
        $url = '';
        if (!is_null($this->logo)) {
            $imgPath = PathHelper::company_images_path($this->id);
            $url = ImageHelper::getImageUrl($imgPath, $this->logo);
        }

        return $url;
    }

    public function getBannerUrlAttribute()
    {
        $url = url('images/reqruit/content-images/company-banner.png');
        if (!is_null($this->banner)) {
            $imgPath = PathHelper::company_images_path($this->id);
            $url = ImageHelper::getImageUrl($imgPath, $this->banner);
        }

        return $url;
    }

    public function getCompanyImagesAttribute()
    {
        $imgPath = PathHelper::company_images_path($this->id);
        $result = [];

        if (is_null($this->images)) {
            return $result;
        }

        foreach ($this->images as $image) {
            $result[] = [
                'new' => false,
                'file_name' => $image['file_name'],
                'src' => ImageHelper::getImageUrl($imgPath, $image['file_name']),
                'description' => $image['description']
            ];
        }

        return $result;
    }
}

app/Http/Controllers/Admin/EmployerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Employer;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Resources\CompanyResource;
use App\Repositories\CompanyRepository;
use App\Http\Resources\EmployerResource;
use App\Repositories\EmployerRepository;

class EmployerController extends Controller
{
    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            $admin = $request->user();
            if ($admin->primary) {
                return $next($request);
            }
            
            if (in_array('manage-employer', $this->getPermissions($admin))) {
                return $next($request);
            } else {
                return redirect()->route('admin.home');
            }
        });
    }

    /**
     * Filter request
     *
     * @param Request $request
     * @return Array
     */
    private function _filters(Request $request)
    {
        return [
            'keyword' => $request->keyword,
            'identifier' => $request->identifier,
            'name' => $request->name,
            'email' => $request->email,
            'phone' => $request->phone,
            'gender' => $request->gender,
            'start_date' => $request->start_date,
            'end_date' => $request->end_date,
        ];
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $employerRepository = new EmployerRepository();
        $employerRepository->adminListRequestValidation($request);

        $employers = Employer::select('*');
        $employerData = $employerRepository->search($employers, $this->_filters($request))->paginate(50);

        $data = [
            'employers' => EmployerResource::collection($employerData),
            'total' => $employerData->total(),
            'per_page' => $employerData->perPage(),
            'current_page' => $employerData->currentPage(),
            'total_page' => $employerData->lastPage(),
            'displayed_start' => (($employerData->currentPage() - 1) * $employerData->perPage()) + 1,
            'displayed_end' => ($employerData->currentPage() == $employerData->lastPage()) ? $employerData->total() : $employerData->currentPage() * $employerData->perPage()
        ];

        if ($request->ajax()) {
            return $this->jsonUnescaped([
                'status' => 'success',
                'data' => $data
            ]);
        }

        return view('admin.employers.index', compact('data'));
    }

    /**
     * Trashed employers
     *
     * @param Request $request
     * @return Mixed Json or blade view
     */
    public function trashed(Request $request)
    {
        $employerRepository = new EmployerRepository();
        $employerRepository->adminListRequestValidation($request);

        $employers = Employer::onlyTrashed();
        $employerData = $employerRepository->search($employers, $this->_filters($request))->paginate(50);

        $data = [
            'employers' => EmployerResource::collection($employerData),
            'total' => $employerData->total(),
            'per_page' => $employerData->perPage(),
            'current_page' => $employerData->currentPage(),
            'total_page' => $employerData->lastPage(),
            'displayed_start' => (($employerData->currentPage() - 1) * $employerData->perPage()) + 1,
            'displayed_end' => ($employerData->currentPage() == $employerData->lastPage()) ? $employerData->total() : $employerData->currentPage() * $employerData->perPage()
        ];

        if ($request->ajax()) {
            return $this->jsonUnescaped([
                'status' => 'success',
                'data' => $data
            ]);
        }

        return view('admin.employers.trashed', compact('data'));
    }

    /**
     * Display the specified resource.
     *
     * @param  Employer  $employer
     * @return \Illuminate\Http\Response
     */
    public function show(Employer $employer)
    {
        $company = $employer->company;
        return view('admin.employers.informations.show', compact('employer', 'company'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Employer  $employer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employer $employer)
    {
        $employer->delete();

        return response()->json([
            'status' => 'success',
            'message' => trans('common.trashed'),
        ]);
    }

    /**
     * Destroy permanent employer
     *
     * @param Int $id
     * @return Json response
     */
    public function destroyPermanent(Int $id)
    {
        $employer = Employer::onlyTrashed()->findOrFail($id);
        $employer->forceDelete();

        return response()->json([
            'status' => 'success',
            'message' => trans('common.permanent_deleted'),
        ]);
    }

    /**
     * Bulk destroy employers
     *
     * @param Request $request
     * @return Json response
     */
    public function bulkDestroy(Request $request)
    {
        $this->validate($request, [
            'ids' => 'required|array'
        ]);

        $employers = Employer::findMany($request->ids);

        foreach ($employers as $employer) {
            $employer->delete();
        }

        return response()->json([
            'status' => 'success',
            'message' => trans('common.trashed'),
        ]);
    }

    /**
     * Bulk destroy permanent employers
     *
     * @param Request $request
     * @return Json response
     */
    public function bulkDestroyPermanent(Request $request)
    {
        $this->validate($request, [
            'ids' => 'required|array'
        ]);

        $employers = Employer::onlyTrashed()->findMany($request->ids);

        foreach ($employers as $employer) {
            $employer->forceDelete();
        }

        return response()->json([
            'status' => 'success',
            'message' => trans('common.permanent_deleted'),
        ]);
    }

    /**
     * Restore employer from trashed
     *
     * @param Int $id
     * @return Json response
     */
    public function restore(Int $id)
    {
        $employer = Employer::onlyTrashed()->findOrFail($id);
        $employer->restore();

        return response()->json([
            'status' => 'success',
            'message' => trans('common.restored'),
        ]);
    }

    /**
     * List of employer companies
     *
     * @param Request $request
     * @param Employer $employer
     * @return Blade view
    */
    public function companies(Request $request, Employer $employer)
    {
        $this->validate($request, [
            'keyword' => 'nullable|string',
            'name' => 'nullable|string',
            'start_date' => 'required_with:end_date|string|date_format:Y-m-d',
            'end_date' => 'required_with:start_date|string|date_format:Y-m-d'
        ]);

        $companies = $employer->companies();
        $companyRepository = new CompanyRepository();
        $filters = [
            'keyword' => $request->keyword,
            'name' => $request->name,
            'start_date' => $request->start_date,
            'end_date' => $request->end_date,
        ];
        $companies = $companyRepository->search($companies, $filters)->paginate(50);

        $data = [
            'employer' => new EmployerResource($employer),
            'companies' => CompanyResource::collection($companies),
            'total' => $companies->total(),
            'per_page' => $companies->perPage(),
            'current_page' => $companies->currentPage(),
            'total_page' => $companies->lastPage(),
            'displayed_start' => (($companies->currentPage() - 1) * $companies->perPage()) + 1,
            'displayed_end' => ($companies->currentPage() == $companies->lastPage()) ? $companies->total() : $companies->currentPage() * $companies->perPage()
        ];

        if ($request->ajax()) {
            return $this->jsonUnescaped([
                'status' => 'success',
                'data' => $data
            ]);
        }

        return view('admin.employers.informations.companies', compact('data', 'employer'));
    }
}

app/Http/Controllers/Api/Employer/AccountController.php
<?php

namespace App\Http\Controllers\Api\Employer;

use Auth;
use employer;
use App\Helpers\PathHelper;
use App\Helpers\ImageHelper;
use Illuminate\Http\Request;
use App\Models\JobApplication;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use App\Http\Requests\PasswordRequest;
use App\Http\Resources\EmployerResource;

class AccountController extends Controller
{
    /**
     * Current logged in employer
     *
     * @var Object
     */
    public $employer;

    /**
     * Class constructor
     */
    public function __construct()
    {
        $this->employer = Auth::guard('employer')->user();
    }

    /**
     * Employer dashboard
     *
     * @param Request $request
     * @return Blade view
     */
    public function dashboard(Request $request)
    {
        $company = $this->employer->company;
        $jobIds = is_null($company) ? [] : $this->employer->company->work_jobs->pluck('id')->toArray();

        $data = [
            'meta_title' => 'Dashboard',
            'meta_description' => 'Company account dashboard',
            'employer' => $this->employer,
            'pending' => JobApplication::whereIn('workjob_id', $jobIds)->where('status', 'pending')->count(),
            'shortlisted' => JobApplication::whereIn('workjob_id', $jobIds)->where('status', 'shortlisted')->count(),
            'interview' => JobApplication::whereIn('workjob_id', $jobIds)->where('status', 'interview')->count(),
            'offered' => JobApplication::whereIn('workjob_id', $jobIds)->where('status', 'offered')->count(),
            'hired' => JobApplication::whereIn('workjob_id', $jobIds)->where('status', 'hired')->count(),
            'unsuitable' => JobApplication::whereIn('workjob_id', $jobIds)->where('status', 'unsuitable')->count(),
        ];

        return $this->successResponse('Employer dashboard', $data);
    }

    /**
     * Edit employer account page
     *
     * @param Request $request
     * @return Blade view
     */
    public function editAccount(Request $request)
    {
        $data = [
            'meta_title' => 'Edit Account',
            'meta_description' => 'Edit account page',
            'employer' => new EmployerResource($this->employer)
        ];

        return $this->successResponse('Edit account', $data);
    }

    /**
     * Update employer account
     *
     * @param Request $request
     * @return Json response
     */
    public function updateAccount(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string',
            'email' => 'required|email|unique:employers,email,'.$this->employer->id,
            'phone' => 'required|string|unique:employers,phone,'.$this->employer->id,
            'gender' => 'required|string|in:male,female',
            'dob' => 'required|date_format:Y-m-d',
        ], [
            'gender.required' => 'Gender is required!',
            'dob.required' => 'Date of birth is required!',
        ]);

        $this->employer->update($request->all());
        $employer = $this->employer->refresh();

        return $this->successResponse('Profile updated', new EmployerResource($employer));
    }

    /**
     * Update password
     *
     * @param Request $request
     * @param PasswordRequest $request
     * @return void
     */
    public function updatePassword(PasswordRequest $request)
    {
        $employer = $this->employer;
        $employer->password = Hash::make($request->new_password);
        $employer->save();

        return $this->successResponse('Password updated', new EmployerResource($employer));
    }

    /**
     * Update employer avatar
     *
     * @param Request $request
     * @return Json response
     */
    public function updateAvatar(Request $request)
    {
        $this->validate($request, [
            'avatar' => 'required|image|mimes:jpg,png,jpeg|max:3000'
        ], [
            'avatar.required' => 'Image is required!',
            'avatar.image' => 'File must be an image!',
            'avatar.mimes' => 'File type must be jpg, png or jpeg!',
            'avatar.max' => 'Max file size 3mb!'
        ]);

        $employer = $this->employer;
        $oldPhoto = $employer->photo;
        $path = PathHelper::employer_photo_path($employer->id);

        // Update photo
        $newPhoto = ImageHelper::processImg($request->avatar, $path, ['type' => 'fit', 'size' => 250], 'avatar');
        $employer->photo = $newPhoto;
        $employer->save();
        
        // Delete old resume
        PathHelper::deleteFile($path.$oldPhoto);

        return $this->successResponse('Avatar updated', new EmployerResource($employer));
    }
}

app/Http/Controllers/Api/Employer/AuthenticatedEmployerController.php
<?php

namespace App\Http\Controllers\Api\Employer;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class AuthenticatedEmployerController extends Controller
{
    
    /**
     * Current logged in employer
     *
     * @var App\Models\Employer
     */
    public $employer;

    /**
     * Class constructor
     */
    public function __construct()
    {
        $this->employer = Auth::guard('employer')->user();
    }
}

resources/views/admin/employers/informations/companies.blade.php
@extends('admin.employers.informations.employers-layout')

@section('employer-information')
    <employer-companies 
        :data="{{ json_encode($data) }}"
    ></employer-companies>
@endsection

resources/views/admin/employers/informations/employers-layout.blade.php
@extends('admin.layouts.app')

@section('content')
<b-container fluid>
    <b-row>
        <b-col md="5" lg="3" class="mb-3 mb-md-3">
            <employer-card :employer="{{ json_encode($employer) }}"></employer-card>
            
            {{-- <b-card class="card-navigation">
                <a 
                    class="nav-link {{ (Request::is('*/employers/'.$employer->id)) ? 'active' : '' }}" 
                    href="{{ route('admin.employers.show', $employer->id) }}"
                >
                    <span class="icon"><i class="far fa-dot-circle"></i></span>
                    <span class="text">Overview</span>
                </a>
    
                <a 
                    class="nav-link {{ (Request::is('*/employers/*/companies')) ? 'active' : '' }}" 
                    href="{{ route('admin.employers.companies', $employer->id) }}"
                >
                    <span class="icon"><i class="far fa-building"></i></span>
                    <span class="text">Companies</span>
                </a>
            </b-card> --}}
        </b-col>
        <div class="col-md-7 col-lg-9">
            @yield('employer-information')
        </div>
    </b-row>
</b-container>
@endsection

resources/views/admin/employers/informations/show.blade.php
@extends('admin.employers.informations.employers-layout')

@section('employer-information')
    <b-card header="Employer Info">
        <div class="row">
            <div class="col-md-12 col-lg-6">
                <table class="table table-sm table-borderless table--width-auto">
                    <tbody>
                        <tr>
                            <th class="label">Identifier</th>
                            <td class="data">{{ $employer->identifier }}</td>
                        </tr>
                        <tr>
                            <th class="label">Name</th>
                            <td class="data">{{ $employer->name }}</td>
                        </tr>
                        <tr>
                            <th class="label">Email</th>
                            <td class="data">{{ $employer->email }}</td>
                        </tr>
                        <tr>
                            <th class="label">Phone</th>
                            <td class="data">{{ $employer->phone ?? '' }}</td>
                        </tr>
                        <tr>
                            <th class="label">Gender</th>
                            <td class="data">{{ $employer->gender ?? '' }}</td>
                        </tr>
                        <tr>
                            <th class="label">Job Position</th>
                            <td class="data">{{ $employer->job_position ?? '' }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-md-12 col-lg-6">
                <table class="table table-sm table-borderless table--width-auto">
                    <tbody>
                        <tr>
                            <th class="label">Date of Birth</th>
                            <td class="data">{{ is_null($employer->dob) ? '' : $employer->dob->format('Y-m-d') }}</td>
                        </tr>
                        <tr>
                            <th class="label">Role</th>
                            <td class="data">{{ $employer->role->description }}</td>
                        </tr>
                        <tr>
                            <th class="label">Created At</th>
                            <td class="data">{{ $employer->created_at }}</td>
                        </tr>
                        <tr>
                            <th class="label">Updated At</th>
                            <td class="data">{{ $employer->updated_at }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        
    </b-card>

    @if (!is_null($company))
        <div class="card mt-4">
            <div class="card-header">Company</div>
            <div class="card-body">
                <div class="row">
                    <div class="col-12 col-md-4 col-lg-3">
                        <img src="{{ $company->logo_url }}" alt="{{ $company->name }}" class="img-fluid">
                    </div>
                    <div class="col-12 col-md-8 col-lg-9">
                        <dl>
                            <dt>Name</dt>
                            <dd>{{ $company->name }}</dd>
    
                            <dt>Address</dt>
                            <dd>{{ $company->city->name }}, <br>{{ $company->province->name }}</dd>
                        </dl>
                        <div class="mt-2">
                            <a href="{{ route('company.index', ['slug' => $company->slug]) }}" title="Company page" target="_blank">Company page <i class="fas fa-external-link-alt"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endif
@endsection